// Generated by onejs-unity's sl plugin from the .sl file beside this one.
// Checked in so the example typechecks without a build step.
declare const program: import("onejs-react").EncodedProgram<"spread">
export default program
/** The file's own text, for showing a program beside what it draws. */
export const source: string
