// Generated by onejs-unity's uss-modules plugin. Checked in so the example
// typechecks without a build step.
declare const styles: {
    readonly tile: string
    readonly tileEmpty: string
    readonly tileFilled: string
    readonly correct: string
    readonly present: string
    readonly absent: string
    readonly key: string
    readonly keyWide: string
    readonly keyNarrow: string
}
export default styles
