// Generated by onejs-unity's uss-modules plugin. Checked in so the example
// typechecks without a build step.
declare const styles: {
    readonly well: string
    readonly cell: string
    readonly i: string
    readonly o: string
    readonly t: string
    readonly s: string
    readonly z: string
    readonly j: string
    readonly l: string
}
export default styles
