// Generated by onejs-unity's uss-modules plugin. Checked in so the example
// typechecks without a build step.
declare const styles: {
    readonly cell: string
    readonly open: string
    readonly slow: string
    readonly wall: string
    readonly visited: string
    readonly frontier: string
    readonly route: string
    readonly start: string
    readonly goal: string
}
export default styles
