// Generated by onejs-unity's uss-modules plugin. Checked in so the example
// typechecks without a build step.
declare const styles: {
    readonly board: string
    readonly cell: string
    readonly tile: string
    readonly popped: string
    readonly fresh: string
    readonly label: string
    readonly v2: string
    readonly v4: string
    readonly v8: string
    readonly v16: string
    readonly v32: string
    readonly v64: string
    readonly v128: string
    readonly v256: string
    readonly v512: string
    readonly v1024: string
    readonly v2048: string
    readonly vHuge: string
    readonly light: string
    readonly dark: string
    readonly veil: string
}
export default styles
